import { getEnvSafely } from './config';

/**
 * For server-used only
 */
const MONGODB_URI = getEnvSafely('MONGODB_URI');
const ACCESS_TOKEN_SECRET = getEnvSafely('ACCESS_TOKEN_SECRET');
const REFRESH_TOKEN_SECRET = getEnvSafely('REFRESH_TOKEN_SECRET');
const GITHUB_ID = getEnvSafely('GITHUB_ID');
const GITHUB_SECRET = getEnvSafely('GITHUB_SECRET');
const GOOGLE_CLIENT_ID = getEnvSafely('GOOGLE_CLIENT_ID');
const GOOGLE_CLIENT_SECRET = getEnvSafely('GOOGLE_CLIENT_SECRET');
const NODE_ENV = getEnvSafely('NODE_ENV');
const NEXTAUTH_SECRET = getEnvSafely('NEXTAUTH_SECRET');
const AUTH_SECRET = getEnvSafely('AUTH_SECRET');
const API_BASE_URL = getEnvSafely('API_BASE_URL');
const NEXTAUTH_URL_INTERNAL = getEnvSafely('NEXTAUTH_URL_INTERNAL');
const NEXT_PUBLIC_API_BASE_URL = getEnvSafely('NEXT_PUBLIC_API_BASE_URL');

const env = {
  MONGODB_URI,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  GITHUB_ID,
  GITHUB_SECRET,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  NODE_ENV,
  NEXTAUTH_SECRET,
  AUTH_SECRET,
  API_BASE_URL,
  NEXTAUTH_URL_INTERNAL,
  NEXT_PUBLIC_API_BASE_URL,
};

export default env;
